language: node_js
sudo: required

addons:
  chrome: stable

node_js:
  - 6
  - 7
  - 8
  - 9 
  - 10 
  - 11 
  - 12 

before_install:
  - dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@^5.8

install:
  - npm ci
  - lerna bootstrap --hoist --npm-ci-mode

script:
  - prettier --list-different '**/*.ts'
  - npm run build
  - npm run bundle
  - npm run test-cov

after_success:
    - 'npm run merge-report && cat coverage/lcov.info | ./node_modules/.bin/coveralls'
